### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by sunsus** [pszklarska/beacon_broadcast#10]
Is the beacon also advertised if the app is in the background?

**Comment by pszklarska** [comment]
Hey @sunsus! For Android yes, it works in the background, for iOS there are some limitations. You can check them in readme - https://github.com/pszklarska/beacon_broadcast#ios

**Comment by al-muammar** [comment]
Hi @pszklarska, it seems that you could overcome this limitation on iOS in the following way: https://stackoverflow.com/questions/18944325/run-iphone-as-an-ibeacon-in-the-background

Any plans to introduce that into a library to make it shine?

**Comment by pszklarska** [comment]
Hi @al-muammar, thanks for that link! This looks promising, I'll see if I can add it to my library 👍
