### ISSUE TITLE
Function .setMajor() isn't working iOS Platform

### ISSUE THREAD

**Issue by LutfiGarzon** [pszklarska/beacon_broadcast#13]
Ok so I configure my environment with no problems whatsoever, there's a bug when I'm trying to configure the Major before starting the broadcast in iOS Platform.
```
beaconBroadcast
            .setUUID(uuid)
            .setIdentifier('com.example.com')
            .setMinorId(0)
            //.setMajorId(100)
            .setTransmissionPower(-59)
            .start();
```

So when I uncommented the line with the function major the app never get running I can't get any feedback from the app.

Edit: 
```
if (Platform.isIOS){
        beaconBroadcast
            .setUUID('$uuid')
            .setMajorId(0) 
            .setMinorId(0) 
            .setIdentifier('$uuid')
            .setTransmissionPower(-59)
            .start();
        debugPrint('iOS');
      } 
```

just close it after updates and review the code I didn't notice more issues I have a hard time back then but now is fully working. this is the code I have right now.

**Comment by pszklarska** [comment]
Hi @LutfiGarzon! Sorry for the late answer, but can you please provide more info about this?

**Comment by LutfiGarzon** [comment]
Maybe someone have the same issue if they have maybe compare their code to mine and see if it works for them.
