### ISSUE TITLE
What kind of range can we expect?

### ISSUE THREAD

**Issue by santhoshraje** [pszklarska/beacon_broadcast#14]
I was wondering what the range of the beacon would be if I used this library. What variables would affect the range of the broadcast?

**Comment by magillus** [comment]
Not sure what you mean about `range of the beacons`.
The range of broadcast is based on signal power of each device. Those max power levels are limited by various organizations and BLE chips itself while manufacturing, so those can be consistent.
Any material blocks signal and some even bounce it.
From my experience beacons are good through a walls and even concrete wall, through some metal cases (like car doors or enclosures) but the power of beacon received by scanner is dropping.

**Comment by santhoshraje** [comment]
Yes, sorry. I mean the range of the broadcast not beacon.
