### ISSUE TITLE
Set interval in advertising parms

### ISSUE THREAD

**Issue by kiokumicu** [pszklarska/beacon_broadcast#17]
Hi!
Thx for your job.
But fir my project there are not enough parameters to set the broadcast frequency.
![FB81DA2D-2FCD-4C56-8AA6-CC2659971DDD](https://user-images.githubusercontent.com/26886/84487816-ff3e2480-aca7-11ea-91da-8f8a8c5e96ea.jpeg)
Is this being solved somehow?

**Comment by Wisbell** [comment]
I'm interested in this as well.  Any information would be appreciated.

**Comment by pszklarska** [comment]
Hey! It landed in 0.2.2, so I'm closing this issue. Thanks everyone for the help!
