### ISSUE TITLE
V2 Embeeding issue

### ISSUE THREAD

**Issue by LutfiGarzon** [pszklarska/beacon_broadcast#28]
The plugin `beacon_broadcast` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration

**Comment by pszklarska** [comment]
Hey @LutfiGarzon thanks for reporting that issue! It's fixed in the newest version (0.3.0)
