### ISSUE TITLE
The library does not work on Android 12

### ISSUE THREAD

**Issue by byblady** [pszklarska/beacon_broadcast#31]
Any solution to this error, it won't let me install the application in android 12

`Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1325317315.tmp/base.apk (at Binary XML file line #90): org.altbeacon.beacon.startup.StartupBroadcastReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]`

@pszklarska 

Thank you for the development of the library.

**Comment by carlosriveroib** [comment]
will you update this?

**Comment by Cryward** [comment]
> will you update this?

I think there will be no more updates, it's been a long time since the problem was reported.

**Comment by carlosriveroib** [comment]
sad and I don't understand why they can just merge the PR should we fork and maintenance this package? Do you have another solution for this?

**Comment by Cryward** [comment]
> sad and I don't understand why they can just merge the PR should we fork and maintenance this package? Do you have another solution for this?

No I don't have a solution for this, it's a pity that the library is not updated, it worked quite well.

**Comment by carlosriveroib** [comment]
What do you think about fork this project and maintenance?

**Comment by Cryward** [comment]
> What do you think about fork this project and maintenance?

I think it should keep updating, at least for me it is very useful and there is no better option so far, someone should take care of updating it, I have no knowledge of how to update a library, otherwise I would gladly do it.

**Comment by pszklarska** [comment]
Hey everyone,
I'm happy to inform you that this issue has been fixed. The newest version 0.3.1 should work on Android 12.
