### ISSUE TITLE
How can I make it working in Flutter v3

### ISSUE THREAD

**Issue by h2magic-axious** [pszklarska/beacon_broadcast#36]
Thanks,

**Comment by h2magic-axious** [comment]
<img width="1875" alt="image" src="https://user-images.githubusercontent.com/48404363/199374360-7aca6c21-8efb-4d73-9b65-21a49797f435.png">

**Comment by pszklarska** [comment]
Hi @h2magic-axious, this issue is most likely caused by the Hot Reload or Hot Restart ([see this](https://stackoverflow.com/a/51244003)). I'm closing it for now,, feel free to re-open if you still encounter this
