### ISSUE TITLE
Check whether a privacy manifest needs to be added

### ISSUE THREAD

**Issue by SoutaTanaka** [pszklarska/beacon_broadcast#39]
First of all, thank you for publishing such a wonderful package. Our project has been greatly helped by this package. 

By the way, starting from April 2024, SDKs used by applications that are published to the Apple App Store need to specify a privacy manifest and digital signature.

I don't think this package requires any additions, but I'd like you, the developer, to confirm.

Apple reached out with the following:

> I lead the Creative Pro Partnership Management team in Apple Worldwide Developer Relations. We manage the relationship with developers who create developer tools, photography, music, 2D/3D design, 3D and gaming pipeline, and production-focused apps and hardware.
>
> As you may know, in June, Apple [announced](https://developer.apple.com/news/?id=av1nevon) new features to help users understand developers’ privacy and data collection and sharing practices. These new features include privacy manifests and signatures, which we encourage all third-party SDKs to adopt to provide transparency to users and help secure the software supply chain. Third-party SDKs that impact user privacy will be expected to include a privacy manifest and signature, and starting in Spring 2024, new and updated apps that include these third-party SDKs will need to include their manifest and signature to submit to the App Store.
>
>Here are some additional resources that may be helpful:
>
>You can read[ documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) about creating a privacy manifest file.
Our [User Privacy and Data Use page](https://developer.apple.com/app-store/user-privacy-and-data-use/) has details about requirements for developers.
You can [watch videos](https://developer.apple.com/videos/privacy-security/) about adopting privacy manifests and signatures for your SDK.

Flutter is tracking this in https://github.com/flutter/flutter/issues/131940

I'm not good at English, so please excuse me if there are any inappropriate sentences.

**Comment by pszklarska** [comment]
Thanks @SoutaTanaka! I'm glad you found the plugin useful for your team.

As far as I know, those changes won't impact `beacon_broadcast` library and the privacy manifest is not required in this case, as it doesn't collect any user's data nor uses any of the required reason API.
