### ISSUE TITLE
Where are the data fields?

### ISSUE THREAD

**Issue by shinayser** [pszklarska/beacon_broadcast#4]
Hello!

Looking into the Android Beacon Library I can see that there is a "setDataFields" method but beacon_broadcast doesn't  exposes it to us.

![image](https://user-images.githubusercontent.com/1146982/61982113-144b8f80-afd2-11e9-93fd-ba0a0f98990f.png)

Being so, how can I set the data my beacon will broacast, like an url or a simple string?

Thank you for your time and effort onto this library!

**Comment by pszklarska** [comment]
Yes, that's right! I'll add this in the next version :)

**Comment by isojtouano** [comment]
Hi @pszklarska , are there any updates on this?

**Comment by darshithedpara** [comment]
Hi @pszklarska @shinayser , are there any updates on this? Really need this update.!

**Comment by pszklarska** [comment]
Hi everyone! Sorry for the late response. 
I'll work on this one this weekend 🙂 I'll keep you guys posted in this issue with any updates about that.

**Comment by darshithedpara** [comment]
@pszklarska  Thanks for getting back and appreciate your help doing this... Please update when you can get this, I am waiting for this since long.

**Comment by pszklarska** [comment]
Hey guys, if you need it urgently, you can checkout changes from the feature/data_fields branch. I haven't tested it fully yet so I'm not publishing it right know, but for now it may be enough.

To check it, replace dependency path in the pubspec.yaml from this:
```
dependencies:
  beacon_broadcast: ^0.2.1
```

To this:
```
dependencies:
  beacon_broadcast: 
    git:
      url: git://github.com/pszklarska/beacon_broadcast.git
      ref: feature/data_fields
```

Let me know if it works.

**Comment by darshithedpara** [comment]
@pszklarska   Thanks for doing this... I will test this and let you know.

**Comment by darshithedpara** [comment]
@pszklarska 
Hi Is there any way to set **connectable** attribute while building the beacon_broadcast ? 

`.setConnectable(false)`

**Comment by pszklarska** [comment]
Hey everyone! It took a while, but the new update (0.2.2) finally has setting data fields :)

@darshithedpara if you still need that, can you please open new issue for `setConnectable()`? I'm closing this one, as it's only for data fields.
